#!/usr/bin/python

import os
import traceback
import pyrouted
from socket import AF_UNIX
from socket import SOCK_STREAM
from socket import fromfd
from socket import socket


##
# create the socket
#
if os.environ.get('LISTEN_PID', None) == str(os.getpid()):
    s = fromfd(3, AF_UNIX, SOCK_STREAM)
else:
    s = socket(AF_UNIX, SOCK_STREAM, 0)
    s.bind(b'\x00pyrouted')
    s.listen(16)
(c, addr) = s.accept()


commands = pyrouted.Commands()
##
# handle the call
#
try:
    transport = pyrouted.Transport(sock=c)
    call = transport.get()
    transport.put(commands(call))
except:
    traceback.print_exc()
finally:
    c.close()
    commands.ipdb.release()
    if os.environ.get('LISTEN_PID', None) != str(os.getpid()):
        s.close()
