#!/usr/bin/python
import sys
import pyrouted
from pprint import pprint
from socket import AF_UNIX
from socket import SOCK_STREAM
from socket import socket

call = {'name': sys.argv[1],
        'argv': sys.argv[2:]}
s = socket(AF_UNIX, SOCK_STREAM, 0)
s.connect("/var/run/pyrouted.sock")

transport = pyrouted.Transport(sock=s)
transport.put(call)
pprint(transport.get())
