#!/usr/bin/python

import os
import traceback
import pyrouted
from socket import AF_UNIX
from socket import SOCK_STREAM
from socket import fromfd
from socket import socket
from pyroute2 import IPDB


##
# create the socket
#
if os.environ.get('LISTEN_PID', None) == str(os.getpid()):
    s = fromfd(3, AF_UNIX, SOCK_STREAM)
else:
    s = socket(AF_UNIX, SOCK_STREAM, 0)
    s.bind(b'\x00pyrouted')
    s.listen(16)
(c, addr) = s.accept()


##
# namespace
#
class Namespace(object):
    def __init__(self):
        self.ipdb = IPDB()

    def get_env(self):
        return dict(os.environ)

    def get_link(self, name='lo'):
        return self.ipdb.interfaces[name]

namespace = Namespace()
##
# handle the call
#
try:
    transport = pyrouted.Transport(sock=c)
    call = transport.get()
    ret = getattr(namespace, call['name'])(*call.get('argv', []),
                                           **call.get('kwarg', {}))
    transport.put(ret)
except:
    traceback.print_exc()
finally:
    c.close()
    namespace.ipdb.release()
    if os.environ.get('LISTEN_PID', None) != str(os.getpid()):
        s.close()
